version: '3.5'

services:
  api:
    image: api
    hostname: app
    build: .
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2GB'
    expose:
      - "80"
    ports:
      - "8080:8080"
    restart: always
  db:
    image: postgres:latest

    environment:
      POSTGRES_DB: banco_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'
    ports:
      - "6050:5432"
    restart: always